[package]
name = "ker"
version = "0.1.0"
edition = "2024"

[dependencies]



ndarray = "0.16.1"
rand = "0.9.0"
ndarray-stats="0.6.0"

plotters = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

csv="1.3.1"



